# Generated by Django 4.1 on 2022-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discription', models.TextField(blank=True, max_length=512, null=True)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
